spring:
  application:
    name: cms-rest

  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/cms_db
    user: postgres
    password: admin