spring:
  application:
    name: cms-rest

  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:/db/migration, classpath:/db/seed

api:
  security:
    token:
      secret:
        ${JWT_SECRET:my-secret-key}