CREATE TABLE countries
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT NOT NULL,
    capital TEXT NOT NULL,
    region TEXT NOT NULL,
    sub_region TEXT NOT NULL,
    area NUMERIC NOT NULL,

    CONSTRAINT pk_employees PRIMARY KEY (id)
);