CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role  TEXT NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE countries
    ADD CONSTRAINT unique_capital UNIQUE (capital),
    ADD COLUMN is_deleted boolean DEFAULT false;

ALTER TABLE users
    ADD COLUMN is_deleted boolean DEFAULT false;

